/**
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAddress.h
 *
 * 
 */

#ifndef OAIAddress_H_
#define OAIAddress_H_

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIAddress: public OAIObject {
public:
    OAIAddress();
    OAIAddress(QString json);
    ~OAIAddress();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIAddress* fromJson(QString jsonString) override;

    QString* getHouseNumber();
    void setHouseNumber(QString* house_number);

    QString* getRoad();
    void setRoad(QString* road);

    QString* getResidential();
    void setResidential(QString* residential);

    QString* getVillage();
    void setVillage(QString* village);

    QString* getCounty();
    void setCounty(QString* county);

    QString* getState();
    void setState(QString* state);

    QString* getPostcode();
    void setPostcode(QString* postcode);

    QString* getCountry();
    void setCountry(QString* country);

    QString* getCountryCode();
    void setCountryCode(QString* country_code);

    QString* getCity();
    void setCity(QString* city);


    virtual bool isSet() override;

private:
    QString* house_number;
    bool m_house_number_isSet;

    QString* road;
    bool m_road_isSet;

    QString* residential;
    bool m_residential_isSet;

    QString* village;
    bool m_village_isSet;

    QString* county;
    bool m_county_isSet;

    QString* state;
    bool m_state_isSet;

    QString* postcode;
    bool m_postcode_isSet;

    QString* country;
    bool m_country_isSet;

    QString* country_code;
    bool m_country_code_isSet;

    QString* city;
    bool m_city_isSet;

};

}

#endif /* OAIAddress_H_ */
