/**
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBalance.h
 *
 * 
 */

#ifndef OAIBalance_H_
#define OAIBalance_H_

#include <QJsonObject>


#include "OAIOAIDaybalance.h"
#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBalance: public OAIObject {
public:
    OAIBalance();
    OAIBalance(QString json);
    ~OAIBalance();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBalance* fromJson(QString jsonString) override;

    QString* getStatus();
    void setStatus(QString* status);

    OAIDaybalance* getBalance();
    void setBalance(OAIDaybalance* balance);


    virtual bool isSet() override;

private:
    QString* status;
    bool m_status_isSet;

    OAIDaybalance* balance;
    bool m_balance_isSet;

};

}

#endif /* OAIBalance_H_ */
