/**
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _OAI_OAIBalanceApi_H_
#define _OAI_OAIBalanceApi_H_

#include "OAIHttpRequest.h"

#include "OAIOAIBalance.h"
#include "OAIOAIError.h"

#include <QObject>

namespace OpenAPI {

class OAIBalanceApi: public QObject {
    Q_OBJECT

public:
    OAIBalanceApi();
    OAIBalanceApi(QString host, QString basePath);
    ~OAIBalanceApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void balance();
    
private:
    void balanceCallback (OAIHttpRequestWorker * worker);
    
signals:
    void balanceSignal(OAIBalance* summary);
    
    void balanceSignalE(OAIBalance* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void balanceSignalEFull(OAIHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
