/**
 * LocationIQ
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDaybalance.h
 *
 * 
 */

#ifndef OAIDaybalance_H_
#define OAIDaybalance_H_

#include <QJsonObject>



#include "OAIObject.h"

namespace OpenAPI {

class OAIDaybalance: public OAIObject {
public:
    OAIDaybalance();
    OAIDaybalance(QString json);
    ~OAIDaybalance();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIDaybalance* fromJson(QString jsonString) override;

    qint32 getDay();
    void setDay(qint32 day);


    virtual bool isSet() override;

private:
    qint32 day;
    bool m_day_isSet;

};

}

#endif /* OAIDaybalance_H_ */
